 const frases = [
  "Deus transforma choro em sorriso e luta em vitória.",
  "A fé em Deus é a força que move montanhas.",
  "Quem confia no Senhor é como um monte inabalável.",
  "Entregue suas dores a Deus e veja milagres acontecerem.",
  "Mesmo no deserto, Deus faz florescer esperança.",
  "Senhor livra-me de todo o perigo.",
  "Nunca peça Vingança a Deus.",
  "Senhor que a tua proteção faça morada na minha vida.",
  "Senhor e meu pastor e nada me faltará.",
  "Senhor eu confio nos teus planos para minha vida.",
  "A minha vida e guardada pelo pai, pelo filho pelo espirito santo",
  "porque eu sei que meu redentor vive e se levantara ao meu favor.",
  "Eu viverei o Efata de Deus",
  "Os impossíveis dos homens são possíveis para Deus.",
  "Senhor livra-me de todo o laço do passarinheiro.",
  "Meu dia hoje será de paz, proteção, Livramento, e prosperidade.",  
  "Na minha casa haverá proteção paz e prosperidade",
  "Senhor toma a dianteira da minha vida",
  "Essa luta não e minha essa luta e Deus",
  "Senhor visita meu passado e quebra toda e qualquer palavra de Maldição",
  "Senhor que a minha prosperidade venha ser para tua gloria",
  "Espírito Santo limpa o meu Coração",
  "Sobretudo tudo que se deve guardar, guarda o seu Coração",
  "Senhor que toda a maldição do Saquitel furado sobre a minha vida caia por terra",
  "Que praga nenhuma chegue na minha Tenda",
  "lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós",
  "Senhor retira do meu Coração toda ansiedade",
  "A minha casa esta protegida pelo sangue de Cristo",
  "Senhor faz morada no meu coração",
  "Reconcilia-te, pois, com ele e tem paz, e assim te sobrevirá o bem",
  "Senhor eu apego a Ti com todo amor do meu Coração",
  "Senhor dai-me Sabedoria",
  "Vigiais e Orais",
  "Senhor me cobre com teu Sangue",
  "A minha vida vai se endireitar-se Gloria a Deus",
  "Deus não permitira que meus pés Vacilem",
  "Se ouvires a voz do SENHOR, teu Deus, virão sobre ti e te alcançarão todas estas bênçãos",
  "O que habita no esconderijo do Altíssimo e descansa à sombra do Onipotente",
   "Nada e do nada para tudo existe um propósito nas coisas de Deus",
   "O Segredo protege a Benção",
   "Senhor Livra minha Vida de toda Inveja",
   "Deus e Grande e esta no controle de Tudo",
   "Eu repreendo todo medo do meu coração é da minha mente em nome do senhor Jesus",
   "Deus esta comigo e eu Estou com Deus",
   "Assim diz o SENHOR: Reprime a tua voz de choro e as lágrimas de teus olhos; porque há recompensa para as tuas obras, diz o SENHOR, pois os teus filhos voltarão da terra do inimigo",
   "Eu recebo a Proteção e o Livramento de Deus contra toda Inveja",
   "Que Deus nos cubra com Sangue do Cordeiro",
   "Tu me cercas por trás e por diante e sobre mim pões a mão",
   "Senhor protege a minha Saúde",
   "Eu recebo a Prosperidade a Proteção e o Socorro Divino",
   "O Senhor e meu Pastor e Nada me Faltara",
   "Deus me levantará em Segurança",
   "Senhor que na minha Vida, Toda a Maldição que estão Lançando se torne Benção",
   "Eu e a Minha Casa Serviremos ao Senhor",
   "Cruel e o Furor Impetuosa e a Ira",
   "Eu sou Protegida por Deus",
   "O Cuidado de Deus esta Presente na Minha vida e na Vida dos meus Familiares",
   "Senhor me dê uma Jornada Feliz a min e a minha Família",
   "Senhor que seja Feita a sua Vontade na Minha Vida",
   "Espera pelo SENHOR, tem bom ânimo, e fortifique-se o teu coração; espera, pois, pelo SENHOR",
  "Senhor Obrigado pois na Minha Vida Tu es Fiel",
  "A minha Vida e a Vida dos meus Familiares estão Guardadas Pelo Pai, Pelo Filho, e Pelo Espirito Santo",
  "Senhor Livrai-me a minha Vida Sentimental de Todos os Males",
  "Na Minha Vida Agindo Deus quem Impedirá",
  "Matheus 6 Vers 6",
  "Tu, porém, quando orares, entra no teu quarto e, fechada a porta, orarás a teu Pai, que está em secreto; e teu Pai, que vê em secreto, te recompensará",
  "A minha Vida Esta Guardada Pelo Pai, Pelo Filho, Pelo Espirito Santo",
  "Senhor Dai-me Saúde e Muitos Anos de Vida",
  "Senhor que a Tua Presença Venha ao meu Encontro",
  "Caiam mil ao meu lado, e dez mil, à minha direita; mas eu não serei atingido",
  "Senhor livra-me de Toda Inveja",
  "Proverbios 27 cap 4",
  "Que todos os Laços Do Inimigo contra Minha Vida Caiam por Terra",
  "Na minha Vida não Haverá nada Faltando nada Quebrado nada Fora do Lugar",
  "Senhor Retira todo Peso Espiritual do meu Corpo",
  "O Meu dia Hoje será Muito Abençoado",
  "Pois disseste: O SENHOR é o meu refúgio. Fizeste do Altíssimo a tua morada",
  "O Meu Deus Iluminará Todos Os Meus Caminhos",
  "Na minha Vida vai da Tudo Certo em Nome do Senhor Jesus",
  "Na Minha Vida e Na Vida do Meu Companheiro Deus Transformará Maldição em Bênçãos",
  "Deus não Permitirá que Meus Pés Vacilem",
  "O SENHOR é o Meu Pastor; Nada Me Faltará",
  "Deus me Livrara do Laço do Passarinheiro",
  "Senhor toma FRENTE da minha vida",
  "Senhor livrai-me e minha Família de Todos os Males Pois Confio em Ti",
  "Deus esta na minha Vida e Por isso sou uma Vencedora",
  "Senhor Livrai-me de Toda Inveja",
  "Leais são as feridas feitas pelo que ama, porém os beijos de quem odeia são enganosos",
  "Crônicas cap 20 vers 15",
  "Isaías 60 Vers 22",
  "O menor virá a ser mil, e o mínimo, uma nação forte; eu, o SENHOR, a seu tempo farei isso prontamente",
  "Na minha vida Deus já Transformou Maldição em Bênção",
  "Deus tem força para Levantar e para fazer Cair",
  "Todos os Meus Sonhos e Projeto Serão Abençoado por Deus",
  "O Senhor pelejará por vós, e vós vos calareis",
  "Senhor Eu Creio nas Suas Promessas",
  "Eu Estou para Viver Grandes Promessas de Deus",
  "Senhor Abra Meus Olhos para que eu Veja",
  "Deus não Melhora ele Muda",
  "Na Minha Vida o Melhor Ficou para o Final",
  "A Mão de Deus esta Sobre a Minha Vida",
  "Senhor Destrava Minha Vida",
  "Mãos Abençoadas, Família Protegida, Bençãos Multiplicadas",
  "Na Minha Família Agir de Deus Quem Impedira",
  "Todas as Portas na Minha Vida Serão Abertas",
  "Deus Vai Me Levantar",
  "Senhor Livrai-me de Toda a Falsidade",
  "Senhor Faz Sua Obra Na Minha Vida",
  "Eu Viverei Coisas Boas e Novas Da Parte de Deus",
  "Senhor Toma a Direção da Minha Vida",
  "Salmo 20",
  "Uns confiam em carros, outros, em cavalos; nós, porém, nos gloriaremos em o nome do SENHOR, nosso Deus",
  "Salmo 23",
  "Ainda que eu ande pelo vale da sombra da morte, não temerei mal nenhum, porque tu estás comigo; o teu bordão e o teu cajado me consolam",
  "Salmo 46",
  "Aquietai-vos e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra",
  "Salmo 70",
  "Eu sou pobre e necessitado; ó Deus, apressa-te em valer-me, pois tu és o meu amparo e o meu libertador. SENHOR, não te detenhas",
  "Salmo 91",
  "Nenhum mal te sucederá, praga nenhuma chegará à tua tenda",
  "A Benção de Efraim Esta Sobre Minha Vida",
  "Salmo 124",
  "O nosso socorro está em o nome do SENHOR, criador do céu e da terra",
  "Salmo 126",
  "Restaura, SENHOR, a nossa sorte, como as torrentes no Neguebe",
  "Senhor Derrama Esse Fio de Unção Sobre Nossas Cabeças",
  "A Minha Benção Vira No De Repente De Deus",
  "Eu Viverei o De Repente de Deus",
  "Erika Reginaldo Nos Seremos Muito Felizes",
  "Senhor E Meu Pastor Nada Me Faltará",
  "Profissional",
  "Na minha Vida não Haverá nada Faltando nada Quebrado nada Fora do Lugar",
  "Senhor Livra A Minha Vida De Todos Os Males",
  "porque Deus não é de confusão, e sim de paz. Como em todas as igrejas dos santos",
  "Na Minha Vida a Maldição Será Transformada Em Bençãos",
  "O Que Não Te Mata, Te Fortalece",
  "Senhor Dai-Me Suade e Muitos Anos de Vida",
  "Senhor Toma a Frente de Tudo Na Minha Vida",
  "Na Minha Vida e Na Vida Do Meu Companheiro Toda Maldição Deus Transformou em Bênçãos",
  "Senhor Me Revela E ao Meu Companheiro O Que Esta Em Oculto e Escondido Que eu Precisamos Saber",
  "Obrigada Senhor por que Ate Aqui o Senhor Nos Ajudou",
  "Quando Deus revela, Deus Quebra",
  "CAMPANHA DE DANIEL",
  "O Meu Testemunho Será Contado",
  "A Insistência Vence A Resistência",
  "Eu estou Guardada No Esconderijo Do Altíssimo",
  "Com A Minha Fé E A Minha Perseverança Em Deus, Eu Terei A Vitória",
  "Senhor que toda Maldição hereditária da minha Família Caia por Terra",
  "Senhor Dai-Me Sabedoria e Discernimento Espiritual",
  "Foste Fiel no Pouco no Muito Te Colocarei",
  "Gratidão Senhor Pela Minha Vida e Pela Vida de Todos Que eu amo",
  "Senhor Obrigado por todo Cuidado que o Senhor Tem na Minha Vida",
  "O Arcanjo Miguel Pelejara Por Min",
  "A Minha Vida Esta Protegida Por Deus",
  "Sopra Seu Vento Na Minha Vida Espírito Santo",
  "Eu Tenho um Deus que Me Guarda e não Me Deixaras Cair",
  "Senhor Retira Toda Pedra de Tropeço da Minha Vida Financeira",
  "Deus esta Quebrando Todo Laço da Minha Vida"
];
function novaFrase() {
  const container = document.getElementById("frases-container");
  const indice = Math.floor(Math.random() * frases.length);
  container.textContent = frases[indice];
}
